name: drupal-sandbox
recipe: drupal9

config:
  php: "8.0"
  via: nginx
  webroot: web
  database: "mariadb:10.3"
  composer_version: 2
  xdebug: off
  config:
    php: .lando/php.ini

tooling:
  grumphp:
    description: "Runs grumphp commands"
    cmd:
      - appserver: ./vendor/bin/grumphp
  npm:
    description: "Runs npm commands"
    service: node
  phpunit:
    description: Runs PHPUnit commands
    user: www-data
    cmd:
      - appserver: "php /app/vendor/bin/phpunit -c /app/phpunit.xml --testdox"
  regenerate-phpunit-config:
    description: "Regenerates fresh PHPUnit configuration."
    cmd:
      - appserver: /app/.lando/phpunit.sh
  xdebug:
    description: "Loads Xdebug in the selected mode"
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root

services:
  database:
    # User random static high port for database connection.
    portforward: 34561
  appserver:
    overrides:
      environment:
        HASH_SALT: notsosecurehash
        ENVIRONMENT_NAME: lando
        DB_NAME_DRUPAL: drupal9
        DB_USER_DRUPAL: drupal9
        DB_PASS_DRUPAL: drupal9
        DB_HOST_DRUPAL: database
        DRUSH_OPTIONS_URI: https://drupal-sandbox.lndo.site
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        PHP_IDE_CONFIG: serverName=appserver
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: "node:16"

proxy:
  mailhog:
    - mail.lndo.site

events:
  post-db-import:
    - appserver: "cd $LANDO_WEBROOT && drush cache:rebuild -y && drush @local user:login"

env_file:
  - .lando/.env

# Tested with Lando version
version: v3.6.4
